name: Delete dev documentation

on:
  pull_request_target:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@fix-token-issue
    with:
      pr_number: ${{ github.event.number }}
      package: accelerate
    secrets:
        token: ${{ secrets.HF_DOC_BUILD_PUSH }}