name: Delete dev documentation trigger

on:
  pull_request:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment_trigger.yml@fix-token-issue
    with:
      pr_number: ${{ github.event.number }}